theme: jekyll-theme-minimal
title: Simple Spring Tutorials
description: This blog helps budding programmers in various Java EE & Spring technologies
show_downloads: false
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - 01_Classic_Java_EE_Architecture.md
  - 02_Spring_Overview.md
  - 03_Spring_Tutorial.md
  - 04_Spring_Tutorial_Using_Annotation.md
  - 05_Spring_AOP_Tutorial.md
  - 06_Spring_JDBC_Tutorial.md
  - 07_Spring_MVC_Tutorial.md
  - 08_Spring_MVC_Form_Basics.md
  - 09_Spring_MVC_Form_Handling.md
  - 10_Spring_REST_Tutorial.md
  - 11_Hibernate_Basics.md